# Funding options for the project
# Remove this file if you don't want to display funding options

github: # Add your GitHub Sponsors username
patreon: # Add your Patreon username
ko_fi: # Add your Ko-fi username
buymecoffee: # Add your Buy Me a Coffee username

# Example:
# github: yourusername
# ko_fi: yourusername